"use client";

import { useState } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Search, Sparkles, AlertCircle, ChevronRight, BookOpen } from "lucide-react";
import { aiApi } from "@/lib/api";

const PRACTICE_AREAS = [
  "", "Criminal Law", "Family Law", "Property Law", "Contract Law",
  "Consumer Protection", "Labour Law", "Constitutional Law",
  "Taxation", "Corporate Law", "Banking Law", "Motor Accident",
];

const COURTS = [
  "", "Supreme Court of India", "High Court", "District Court",
  "Consumer Forum", "Labour Court", "Tribunal", "Sessions Court",
];

interface IssueResult {
  issues: string[];
  primary_issue: string;
  applicable_laws: string[];
  total_issues: number;
  powered_by: string;
}

export default function IssueSpotterPage() {
  const [form, setForm] = useState({
    case_facts: "",
    practice_area: "",
    court: "",
  });
  const [result, setResult] = useState<IssueResult | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSpot = async () => {
    if (!form.case_facts.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const { data } = await aiApi.post("/legal-tasks/issue-spotter", form);
      setResult(data);
    } catch {
      setResult({
        issues: ["Unable to identify issues. Please try again."],
        primary_issue: "",
        applicable_laws: [],
        total_issues: 0,
        powered_by: "Error",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <AppLayout requirePro title="Issue Spotter" subtitle="Identify key legal issues from case facts — powered by Aalap (OpenNyAI)">
      <div className="max-w-4xl mx-auto space-y-6">

        {/* Input */}
        <div className="vk-card p-6 space-y-4">
          <div className="flex items-center gap-2 mb-1">
            <Search className="w-4 h-4" style={{ color: "var(--vk-gold)" }} />
            <h3 className="font-semibold text-sm">Case Facts</h3>
            <span className="vk-badge vk-badge-gold text-[10px] ml-auto">Aalap AI</span>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="vk-label">Case Facts / Dispute Description *</label>
              <textarea
                className="vk-input w-full h-36 resize-none"
                placeholder="Describe the full facts of the case — background, events, parties, what dispute arose, relevant dates and amounts..."
                value={form.case_facts}
                onChange={e => setForm(f => ({ ...f, case_facts: e.target.value }))}
              />
            </div>
            <div>
              <label className="vk-label">Practice Area (optional)</label>
              <select className="vk-input w-full" value={form.practice_area} onChange={e => setForm(f => ({ ...f, practice_area: e.target.value }))}>
                {PRACTICE_AREAS.map(a => <option key={a} value={a}>{a || "Auto-detect"}</option>)}
              </select>
            </div>
            <div>
              <label className="vk-label">Court / Forum (optional)</label>
              <select className="vk-input w-full" value={form.court} onChange={e => setForm(f => ({ ...f, court: e.target.value }))}>
                {COURTS.map(c => <option key={c} value={c}>{c || "Not specified"}</option>)}
              </select>
            </div>
          </div>

          <button
            className="btn-primary py-2.5 px-6 flex items-center gap-2"
            onClick={handleSpot}
            disabled={loading || !form.case_facts.trim()}
          >
            <Sparkles className="w-4 h-4" />
            {loading ? "Spotting Issues..." : "Spot Legal Issues"}
          </button>
        </div>

        {loading && (
          <div className="space-y-3">
            <div className="vk-skeleton h-20 rounded-xl" />
            <div className="vk-skeleton h-48 rounded-xl" />
          </div>
        )}

        {result && !loading && (
          <div className="space-y-4">
            <p className="text-xs text-dim">
              Generated by <span style={{ color: "var(--vk-gold)" }}>{result.powered_by}</span>
              {" · "}{result.total_issues} issue{result.total_issues !== 1 ? "s" : ""} identified
            </p>

            {/* Primary issue callout */}
            {result.primary_issue && (
              <div className="vk-card p-4" style={{ border: "1px solid rgba(201,168,76,0.3)", background: "rgba(201,168,76,0.06)" }}>
                <p className="text-[10px] font-semibold uppercase tracking-widest mb-1.5" style={{ color: "var(--vk-gold)" }}>
                  Primary Issue for Determination
                </p>
                <p className="text-sm font-semibold leading-relaxed" style={{ color: "var(--vk-text)" }}>
                  {result.primary_issue}
                </p>
              </div>
            )}

            {/* All issues */}
            <div className="vk-card p-5 space-y-3">
              <h3 className="font-semibold text-sm">All Legal Issues</h3>
              <div className="space-y-2">
                {result.issues.map((issue, i) => (
                  <div key={i} className="flex items-start gap-3 rounded-lg p-3" style={{ background: "rgba(255,255,255,0.03)" }}>
                    <span className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold"
                      style={{ background: "rgba(201,168,76,0.15)", color: "var(--vk-gold)" }}>
                      {i + 1}
                    </span>
                    <div className="flex-1">
                      <p className="text-sm leading-relaxed" style={{ color: "var(--vk-text)" }}>{issue}</p>
                    </div>
                    <ChevronRight className="w-4 h-4 text-dim shrink-0 mt-0.5" />
                  </div>
                ))}
              </div>
            </div>

            {/* Applicable laws */}
            {result.applicable_laws.length > 0 && (
              <div className="vk-card p-4 space-y-3">
                <div className="flex items-center gap-2">
                  <BookOpen className="w-4 h-4" style={{ color: "var(--vk-gold)" }} />
                  <h3 className="font-semibold text-sm">Applicable Laws & Statutes</h3>
                </div>
                <div className="flex flex-wrap gap-2">
                  {result.applicable_laws.map((law, i) => (
                    <span key={i} className="vk-badge vk-badge-gold text-xs">{law}</span>
                  ))}
                </div>
              </div>
            )}

            <div className="vk-disclaimer rounded-xl p-4 text-xs text-dim">
              <AlertCircle className="w-3.5 h-3.5 inline mr-1.5" />
              AI-identified issues are a research aid. Framing of issues may differ in actual pleadings. Consult a qualified advocate before filing.
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
