"use client";

import { useState } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Clock, Sparkles, AlertCircle, Calendar, FileText } from "lucide-react";
import { aiApi } from "@/lib/api";

interface TimelineEvent {
  date: string;
  event: string;
  significance: string;
}

interface TimelineResult {
  events: TimelineEvent[];
  total_events: number;
  source_type: string;
  powered_by: string;
}

const DOT_COLORS = [
  "var(--vk-gold)",
  "#60a5fa",
  "#4ade80",
  "#f87171",
  "#a78bfa",
  "#fb923c",
];

export default function EventTimelinePage() {
  const [caseDescription, setCaseDescription] = useState("");
  const [sourceType, setSourceType] = useState<"case" | "fir">("case");
  const [result, setResult] = useState<TimelineResult | null>(null);
  const [loading, setLoading] = useState(false);

  const handleExtract = async () => {
    if (!caseDescription.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      const { data } = await aiApi.post("/legal-tasks/event-timeline", {
        case_description: caseDescription,
        source_type: sourceType,
      });
      setResult(data);
    } catch {
      setResult({
        events: [{ date: "", event: "Unable to extract timeline. Please try again.", significance: "" }],
        total_events: 0,
        source_type: sourceType,
        powered_by: "Error",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <AppLayout requirePro title="Event Timeline" subtitle="Extract chronological events from case facts or FIR — powered by Aalap (OpenNyAI)">
      <div className="max-w-4xl mx-auto space-y-6">

        {/* Input */}
        <div className="vk-card p-6 space-y-4">
          <div className="flex items-center gap-2 mb-1">
            <Clock className="w-4 h-4" style={{ color: "var(--vk-gold)" }} />
            <h3 className="font-semibold text-sm">Input</h3>
            <span className="vk-badge vk-badge-gold text-[10px] ml-auto">Aalap AI</span>
          </div>

          {/* Source type toggle */}
          <div className="flex gap-1 p-1 rounded-lg w-fit" style={{ background: "var(--vk-navy-dark)" }}>
            {[
              { key: "case", label: "Case Description", icon: FileText },
              { key: "fir", label: "FIR / Police Report", icon: AlertCircle },
            ].map(t => {
              const Icon = t.icon;
              return (
                <button
                  key={t.key}
                  className={`flex items-center gap-1.5 text-xs py-1.5 px-3 rounded-md font-semibold transition-colors ${sourceType === t.key ? "text-navy" : "text-dim"}`}
                  style={sourceType === t.key ? { background: "var(--vk-gold)" } : {}}
                  onClick={() => setSourceType(t.key as "case" | "fir")}
                >
                  <Icon className="w-3.5 h-3.5" />
                  {t.label}
                </button>
              );
            })}
          </div>

          <div>
            <label className="vk-label">
              {sourceType === "fir" ? "FIR / Police Report Text *" : "Case Description / Judgment Text *"}
            </label>
            <textarea
              className="vk-input w-full h-40 resize-none"
              placeholder={
                sourceType === "fir"
                  ? "Paste the FIR text or complainant's statement here — include all dates, times, and events mentioned..."
                  : "Paste the case facts, pleadings, or judgment text — include all relevant dates, orders, hearings, and events..."
              }
              value={caseDescription}
              onChange={e => setCaseDescription(e.target.value)}
            />
          </div>

          <button
            className="btn-primary py-2.5 px-6 flex items-center gap-2"
            onClick={handleExtract}
            disabled={loading || !caseDescription.trim()}
          >
            <Sparkles className="w-4 h-4" />
            {loading ? "Extracting Timeline..." : "Extract Timeline"}
          </button>
        </div>

        {loading && (
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => <div key={i} className="vk-skeleton h-16 rounded-xl" />)}
          </div>
        )}

        {result && !loading && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <p className="text-xs text-dim">
                Generated by <span style={{ color: "var(--vk-gold)" }}>{result.powered_by}</span>
                {" · "}{result.total_events} events extracted
              </p>
              <span className="vk-badge vk-badge-muted text-xs">
                {result.source_type === "fir" ? "FIR Analysis" : "Case Timeline"}
              </span>
            </div>

            {/* Timeline */}
            <div className="vk-card p-6">
              <div className="relative">
                {/* Vertical line */}
                <div
                  className="absolute left-[18px] top-4 bottom-4 w-px"
                  style={{ background: "var(--vk-border)" }}
                />

                <div className="space-y-5">
                  {result.events.map((event, i) => (
                    <div key={i} className="flex items-start gap-4 relative">
                      {/* Dot */}
                      <div
                        className="shrink-0 w-9 h-9 rounded-full flex items-center justify-center z-10"
                        style={{
                          background: `${DOT_COLORS[i % DOT_COLORS.length]}18`,
                          border: `2px solid ${DOT_COLORS[i % DOT_COLORS.length]}`,
                        }}
                      >
                        <Calendar className="w-4 h-4" style={{ color: DOT_COLORS[i % DOT_COLORS.length] }} />
                      </div>

                      {/* Content */}
                      <div className="flex-1 pb-1">
                        {event.date && (
                          <p className="text-xs font-bold mb-0.5" style={{ color: DOT_COLORS[i % DOT_COLORS.length] }}>
                            {event.date}
                          </p>
                        )}
                        <p className="text-sm font-semibold leading-snug" style={{ color: "var(--vk-text)" }}>
                          {event.event}
                        </p>
                        {event.significance && (
                          <p className="text-xs text-dim mt-1 leading-relaxed">{event.significance}</p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="vk-disclaimer rounded-xl p-4 text-xs text-dim">
              <AlertCircle className="w-3.5 h-3.5 inline mr-1.5" />
              AI-extracted timelines may miss events or assign approximate dates. Verify against source documents before use in proceedings.
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
