/**
 * India State → District → City data for cascading location selectors.
 *
 * Districts are fairly complete per state; city lists are best-effort (district
 * HQ plus notable towns) and intentionally partial — the UI always offers an
 * "Other…" option that reveals a free-text input, so anything not listed here
 * can still be entered.
 */

export type CityList = string[];
export type DistrictMap = Record<string, CityList>;
export type StateMap = Record<string, DistrictMap>;

export const INDIA_LOCATIONS: StateMap = {
  "Andhra Pradesh": {
    "Anantapur": ["Anantapur", "Hindupur", "Guntakal", "Tadipatri"],
    "Chittoor": ["Chittoor", "Tirupati", "Madanapalle", "Srikalahasti"],
    "East Godavari": ["Kakinada", "Rajahmundry", "Amalapuram"],
    "Guntur": ["Guntur", "Tenali", "Narasaraopet", "Bapatla"],
    "Krishna": ["Machilipatnam", "Vijayawada", "Gudivada"],
    "Kurnool": ["Kurnool", "Nandyal", "Adoni", "Yemmiganur"],
    "Nellore": ["Nellore", "Kavali", "Gudur"],
    "Prakasam": ["Ongole", "Chirala", "Markapur"],
    "Srikakulam": ["Srikakulam", "Palasa", "Amadalavalasa"],
    "Visakhapatnam": ["Visakhapatnam", "Anakapalle", "Bheemunipatnam"],
    "Vizianagaram": ["Vizianagaram", "Bobbili", "Parvathipuram"],
    "West Godavari": ["Eluru", "Bhimavaram", "Tadepalligudem", "Narsapur"],
    "YSR Kadapa": ["Kadapa", "Proddatur", "Pulivendula"],
  },
  "Arunachal Pradesh": {
    "Itanagar Capital Complex": ["Itanagar", "Naharlagun"],
    "Tawang": ["Tawang"],
    "West Kameng": ["Bomdila"],
    "East Siang": ["Pasighat"],
    "Lohit": ["Tezu"],
    "Changlang": ["Changlang"],
    "Papum Pare": ["Yupia"],
  },
  "Assam": {
    "Kamrup Metropolitan": ["Guwahati", "Dispur"],
    "Kamrup": ["Amingaon", "Rangia"],
    "Cachar": ["Silchar"],
    "Dibrugarh": ["Dibrugarh"],
    "Nagaon": ["Nagaon"],
    "Jorhat": ["Jorhat"],
    "Sivasagar": ["Sivasagar"],
    "Tinsukia": ["Tinsukia"],
    "Barpeta": ["Barpeta"],
    "Sonitpur": ["Tezpur"],
  },
  "Bihar": {
    "Patna": ["Patna", "Danapur", "Barh"],
    "Gaya": ["Gaya", "Bodh Gaya"],
    "Bhagalpur": ["Bhagalpur"],
    "Muzaffarpur": ["Muzaffarpur"],
    "Darbhanga": ["Darbhanga"],
    "Purnia": ["Purnia"],
    "Nalanda": ["Bihar Sharif"],
    "Begusarai": ["Begusarai"],
    "Bhojpur": ["Arrah"],
    "Rohtas": ["Sasaram", "Dehri"],
    "Saran": ["Chapra"],
    "East Champaran": ["Motihari"],
    "West Champaran": ["Bettiah", "Bagaha"],
  },
  "Chhattisgarh": {
    "Raipur": ["Raipur"],
    "Bilaspur": ["Bilaspur"],
    "Durg": ["Durg", "Bhilai"],
    "Korba": ["Korba"],
    "Raigarh": ["Raigarh"],
    "Rajnandgaon": ["Rajnandgaon"],
    "Jagdalpur (Bastar)": ["Jagdalpur"],
    "Ambikapur (Surguja)": ["Ambikapur"],
  },
  "Goa": {
    "North Goa": ["Panaji", "Mapusa", "Bicholim", "Ponda"],
    "South Goa": ["Margao", "Vasco da Gama", "Curchorem"],
  },
  "Gujarat": {
    "Ahmedabad": ["Ahmedabad", "Sanand", "Dholka"],
    "Surat": ["Surat", "Bardoli"],
    "Vadodara": ["Vadodara", "Dabhoi"],
    "Rajkot": ["Rajkot", "Gondal", "Jetpur"],
    "Bhavnagar": ["Bhavnagar", "Palitana"],
    "Jamnagar": ["Jamnagar", "Dwarka"],
    "Junagadh": ["Junagadh", "Veraval"],
    "Gandhinagar": ["Gandhinagar", "Kalol"],
    "Kutch": ["Bhuj", "Gandhidham", "Anjar"],
    "Anand": ["Anand", "Vallabh Vidyanagar"],
    "Mehsana": ["Mehsana"],
    "Kheda": ["Nadiad"],
    "Navsari": ["Navsari"],
    "Valsad": ["Valsad", "Vapi"],
  },
  "Haryana": {
    "Gurugram": ["Gurugram", "Manesar", "Sohna"],
    "Faridabad": ["Faridabad", "Ballabgarh"],
    "Hisar": ["Hisar", "Hansi"],
    "Rohtak": ["Rohtak"],
    "Panipat": ["Panipat"],
    "Karnal": ["Karnal", "Gharaunda"],
    "Ambala": ["Ambala", "Ambala Cantt"],
    "Yamunanagar": ["Yamunanagar", "Jagadhri"],
    "Sonipat": ["Sonipat", "Gohana"],
    "Panchkula": ["Panchkula", "Kalka"],
    "Sirsa": ["Sirsa"],
    "Bhiwani": ["Bhiwani"],
    "Rewari": ["Rewari"],
  },
  "Himachal Pradesh": {
    "Shimla": ["Shimla", "Rampur"],
    "Kangra": ["Dharamshala", "Palampur", "Kangra"],
    "Mandi": ["Mandi", "Sundernagar"],
    "Solan": ["Solan", "Nalagarh", "Baddi"],
    "Kullu": ["Kullu", "Manali"],
    "Una": ["Una"],
    "Hamirpur": ["Hamirpur"],
    "Bilaspur": ["Bilaspur"],
    "Chamba": ["Chamba"],
    "Sirmaur": ["Nahan"],
  },
  "Jharkhand": {
    "Ranchi": ["Ranchi"],
    "Dhanbad": ["Dhanbad"],
    "East Singhbhum": ["Jamshedpur"],
    "Bokaro": ["Bokaro Steel City"],
    "Hazaribagh": ["Hazaribagh"],
    "Deoghar": ["Deoghar"],
    "Giridih": ["Giridih"],
    "Palamu": ["Daltonganj"],
    "Dumka": ["Dumka"],
  },
  "Karnataka": {
    "Bengaluru Urban": ["Bengaluru", "Whitefield", "Yelahanka"],
    "Bengaluru Rural": ["Devanahalli", "Doddaballapura", "Hoskote"],
    "Mysuru": ["Mysuru", "Nanjangud"],
    "Belagavi": ["Belagavi", "Gokak"],
    "Kalaburagi": ["Kalaburagi"],
    "Mangaluru (Dakshina Kannada)": ["Mangaluru", "Puttur"],
    "Dharwad": ["Hubballi", "Dharwad"],
    "Ballari": ["Ballari", "Hospet"],
    "Vijayapura": ["Vijayapura"],
    "Tumakuru": ["Tumakuru"],
    "Shivamogga": ["Shivamogga", "Bhadravati"],
    "Davanagere": ["Davanagere"],
    "Udupi": ["Udupi", "Manipal"],
    "Hassan": ["Hassan"],
    "Mandya": ["Mandya"],
  },
  "Kerala": {
    "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Attingal"],
    "Kollam": ["Kollam", "Punalur"],
    "Pathanamthitta": ["Pathanamthitta", "Adoor"],
    "Alappuzha": ["Alappuzha", "Cherthala"],
    "Kottayam": ["Kottayam", "Changanassery"],
    "Idukki": ["Painavu", "Munnar", "Thodupuzha"],
    "Ernakulam": ["Kochi", "Aluva", "Perumbavoor"],
    "Thrissur": ["Thrissur", "Chalakudy", "Guruvayur"],
    "Palakkad": ["Palakkad", "Ottappalam"],
    "Malappuram": ["Malappuram", "Manjeri", "Tirur"],
    "Kozhikode": ["Kozhikode", "Vadakara"],
    "Wayanad": ["Kalpetta", "Sultan Bathery"],
    "Kannur": ["Kannur", "Thalassery", "Payyanur"],
    "Kasaragod": ["Kasaragod", "Kanhangad"],
  },
  "Madhya Pradesh": {
    "Bhopal": ["Bhopal"],
    "Indore": ["Indore", "Mhow"],
    "Jabalpur": ["Jabalpur"],
    "Gwalior": ["Gwalior"],
    "Ujjain": ["Ujjain"],
    "Sagar": ["Sagar"],
    "Rewa": ["Rewa"],
    "Satna": ["Satna"],
    "Ratlam": ["Ratlam"],
    "Dewas": ["Dewas"],
    "Chhindwara": ["Chhindwara"],
    "Katni": ["Katni"],
  },
  "Maharashtra": {
    "Mumbai City": ["Mumbai"],
    "Mumbai Suburban": ["Andheri", "Borivali", "Kurla", "Bandra"],
    "Thane": ["Thane", "Kalyan", "Bhiwandi", "Ulhasnagar"],
    "Palghar": ["Palghar", "Vasai-Virar", "Boisar"],
    "Pune": ["Pune", "Pimpri-Chinchwad", "Baramati"],
    "Nagpur": ["Nagpur", "Kamptee"],
    "Nashik": ["Nashik", "Malegaon", "Manmad"],
    "Aurangabad (Chhatrapati Sambhajinagar)": ["Aurangabad", "Gangapur"],
    "Solapur": ["Solapur", "Pandharpur"],
    "Kolhapur": ["Kolhapur", "Ichalkaranji"],
    "Amravati": ["Amravati", "Achalpur"],
    "Nanded": ["Nanded"],
    "Sangli": ["Sangli", "Miraj"],
    "Jalgaon": ["Jalgaon", "Bhusawal"],
    "Ahmednagar": ["Ahmednagar", "Shirdi"],
    "Satara": ["Satara", "Karad"],
    "Raigad": ["Alibag", "Panvel"],
    "Ratnagiri": ["Ratnagiri", "Chiplun"],
  },
  "Manipur": {
    "Imphal West": ["Imphal"],
    "Imphal East": ["Porompat"],
    "Thoubal": ["Thoubal"],
    "Bishnupur": ["Bishnupur"],
    "Churachandpur": ["Churachandpur"],
  },
  "Meghalaya": {
    "East Khasi Hills": ["Shillong"],
    "West Garo Hills": ["Tura"],
    "Ri Bhoi": ["Nongpoh"],
    "Jaintia Hills": ["Jowai"],
  },
  "Mizoram": {
    "Aizawl": ["Aizawl"],
    "Lunglei": ["Lunglei"],
    "Champhai": ["Champhai"],
    "Kolasib": ["Kolasib"],
  },
  "Nagaland": {
    "Kohima": ["Kohima"],
    "Dimapur": ["Dimapur"],
    "Mokokchung": ["Mokokchung"],
    "Tuensang": ["Tuensang"],
  },
  "Odisha": {
    "Khordha": ["Bhubaneswar", "Khordha", "Jatani"],
    "Cuttack": ["Cuttack", "Choudwar"],
    "Ganjam": ["Berhampur", "Chhatrapur"],
    "Sundargarh": ["Rourkela", "Sundargarh"],
    "Sambalpur": ["Sambalpur"],
    "Balasore": ["Balasore"],
    "Puri": ["Puri"],
    "Mayurbhanj": ["Baripada"],
    "Angul": ["Angul"],
  },
  "Punjab": {
    "Ludhiana": ["Ludhiana", "Khanna", "Jagraon"],
    "Amritsar": ["Amritsar", "Rajasansi"],
    "Jalandhar": ["Jalandhar", "Nakodar"],
    "Patiala": ["Patiala", "Rajpura", "Nabha"],
    "Bathinda": ["Bathinda", "Rampura Phul"],
    "Mohali (SAS Nagar)": ["Mohali", "Kharar", "Zirakpur"],
    "Hoshiarpur": ["Hoshiarpur"],
    "Pathankot": ["Pathankot"],
    "Moga": ["Moga"],
    "Firozpur": ["Firozpur"],
    "Sangrur": ["Sangrur", "Malerkotla"],
    "Fatehgarh Sahib": ["Sirhind", "Fatehgarh Sahib"],
  },
  "Rajasthan": {
    "Jaipur": ["Jaipur", "Chomu", "Bagru"],
    "Jodhpur": ["Jodhpur", "Phalodi"],
    "Udaipur": ["Udaipur"],
    "Kota": ["Kota"],
    "Ajmer": ["Ajmer", "Kishangarh", "Beawar"],
    "Bikaner": ["Bikaner"],
    "Alwar": ["Alwar", "Bhiwadi"],
    "Bharatpur": ["Bharatpur"],
    "Sikar": ["Sikar"],
    "Bhilwara": ["Bhilwara"],
    "Sri Ganganagar": ["Sri Ganganagar"],
    "Pali": ["Pali"],
  },
  "Sikkim": {
    "Gangtok (East Sikkim)": ["Gangtok"],
    "Namchi (South Sikkim)": ["Namchi"],
    "Gyalshing (West Sikkim)": ["Gyalshing", "Pelling"],
    "Mangan (North Sikkim)": ["Mangan"],
  },
  "Tamil Nadu": {
    "Chennai": ["Chennai", "Ambattur", "Tambaram"],
    "Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam"],
    "Madurai": ["Madurai", "Melur"],
    "Tiruchirappalli": ["Tiruchirappalli", "Srirangam"],
    "Salem": ["Salem", "Attur"],
    "Tirunelveli": ["Tirunelveli", "Palayamkottai"],
    "Erode": ["Erode", "Gobichettipalayam"],
    "Vellore": ["Vellore", "Gudiyatham"],
    "Thoothukudi": ["Thoothukudi", "Kovilpatti"],
    "Dindigul": ["Dindigul", "Palani"],
    "Thanjavur": ["Thanjavur", "Kumbakonam"],
    "Kanchipuram": ["Kanchipuram"],
    "Chengalpattu": ["Chengalpattu", "Maraimalai Nagar"],
    "Tiruppur": ["Tiruppur"],
    "Nagercoil (Kanyakumari)": ["Nagercoil"],
  },
  "Telangana": {
    "Hyderabad": ["Hyderabad"],
    "Rangareddy": ["Shamshabad", "Ibrahimpatnam"],
    "Medchal-Malkajgiri": ["Malkajgiri", "Kompally"],
    "Warangal": ["Warangal", "Hanamkonda"],
    "Karimnagar": ["Karimnagar"],
    "Khammam": ["Khammam"],
    "Nizamabad": ["Nizamabad"],
    "Nalgonda": ["Nalgonda"],
    "Mahbubnagar": ["Mahbubnagar"],
    "Sangareddy": ["Sangareddy"],
  },
  "Tripura": {
    "West Tripura": ["Agartala"],
    "Gomati": ["Udaipur"],
    "North Tripura": ["Dharmanagar"],
    "Unakoti": ["Kailashahar"],
  },
  "Uttar Pradesh": {
    "Lucknow": ["Lucknow"],
    "Kanpur Nagar": ["Kanpur"],
    "Agra": ["Agra"],
    "Varanasi": ["Varanasi"],
    "Prayagraj": ["Prayagraj"],
    "Meerut": ["Meerut"],
    "Ghaziabad": ["Ghaziabad", "Loni", "Modinagar"],
    "Gautam Buddha Nagar": ["Noida", "Greater Noida", "Dadri"],
    "Bareilly": ["Bareilly"],
    "Aligarh": ["Aligarh"],
    "Moradabad": ["Moradabad"],
    "Gorakhpur": ["Gorakhpur"],
    "Saharanpur": ["Saharanpur"],
    "Jhansi": ["Jhansi"],
    "Mathura": ["Mathura", "Vrindavan"],
    "Ayodhya": ["Ayodhya", "Faizabad"],
    "Firozabad": ["Firozabad"],
    "Muzaffarnagar": ["Muzaffarnagar"],
  },
  "Uttarakhand": {
    "Dehradun": ["Dehradun", "Rishikesh", "Mussoorie"],
    "Haridwar": ["Haridwar", "Roorkee"],
    "Nainital": ["Nainital", "Haldwani"],
    "Udham Singh Nagar": ["Rudrapur", "Kashipur"],
    "Pauri Garhwal": ["Pauri", "Kotdwar"],
    "Almora": ["Almora"],
    "Tehri Garhwal": ["New Tehri"],
    "Chamoli": ["Gopeshwar", "Joshimath"],
  },
  "West Bengal": {
    "Kolkata": ["Kolkata"],
    "North 24 Parganas": ["Barasat", "Barrackpore", "Bidhannagar"],
    "South 24 Parganas": ["Alipore", "Diamond Harbour", "Baruipur"],
    "Howrah": ["Howrah"],
    "Hooghly": ["Chinsurah", "Serampore", "Chandannagar"],
    "Paschim Bardhaman": ["Asansol", "Durgapur"],
    "Purba Bardhaman": ["Bardhaman"],
    "Darjeeling": ["Darjeeling", "Siliguri"],
    "Nadia": ["Krishnanagar", "Kalyani"],
    "Murshidabad": ["Berhampore"],
    "Malda": ["English Bazar"],
    "Jalpaiguri": ["Jalpaiguri"],
  },
  // ── Union Territories ──
  "Andaman and Nicobar Islands": {
    "South Andaman": ["Port Blair"],
    "North and Middle Andaman": ["Mayabunder", "Rangat"],
    "Nicobar": ["Car Nicobar"],
  },
  "Chandigarh": {
    "Chandigarh": ["Chandigarh"],
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa"],
    "Daman": ["Daman"],
    "Diu": ["Diu"],
  },
  "Delhi": {
    "New Delhi": ["New Delhi", "Connaught Place", "Chanakyapuri"],
    "Central Delhi": ["Daryaganj", "Karol Bagh", "Paharganj"],
    "North Delhi": ["Civil Lines", "Model Town"],
    "South Delhi": ["Saket", "Hauz Khas", "Greater Kailash"],
    "East Delhi": ["Preet Vihar", "Mayur Vihar", "Laxmi Nagar"],
    "West Delhi": ["Rajouri Garden", "Janakpuri", "Tilak Nagar"],
    "North East Delhi": ["Seelampur", "Shahdara"],
    "North West Delhi": ["Rohini", "Pitampura"],
    "South West Delhi": ["Dwarka", "Najafgarh"],
    "South East Delhi": ["Nehru Place", "Kalkaji"],
    "Shahdara": ["Shahdara"],
  },
  "Jammu and Kashmir": {
    "Srinagar": ["Srinagar"],
    "Jammu": ["Jammu"],
    "Anantnag": ["Anantnag"],
    "Baramulla": ["Baramulla"],
    "Udhampur": ["Udhampur"],
    "Kathua": ["Kathua"],
  },
  "Ladakh": {
    "Leh": ["Leh"],
    "Kargil": ["Kargil"],
  },
  "Lakshadweep": {
    "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy"],
  },
  "Puducherry": {
    "Puducherry": ["Puducherry"],
    "Karaikal": ["Karaikal"],
    "Mahe": ["Mahe"],
    "Yanam": ["Yanam"],
  },
};

/** All states and union territories, alphabetically. */
export const INDIAN_STATES_UT: string[] = Object.keys(INDIA_LOCATIONS).sort();

/** Districts for a given state (sorted). Empty array if unknown. */
export function districtsOf(state: string): string[] {
  const m = INDIA_LOCATIONS[state];
  return m ? Object.keys(m).sort() : [];
}

/** Cities for a given state + district (sorted). Empty array if unknown. */
export function citiesOf(state: string, district: string): string[] {
  const cities = INDIA_LOCATIONS[state]?.[district];
  return cities ? [...cities].sort() : [];
}

/** Sentinel value used by the selectors to reveal a free-text input. */
export const OTHER_OPTION = "__other__";
